using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


public class RawStatsDto
{
	public int assists;
    public int barracksKilled;
    public int championsKilled;
    public int combatPlayerScore;
    public int consumablesPurchased;	
    public int damageDealtPlayer;
    public int doubleKills;
    public int firstBlood;
    public int gold;
    public int goldEarned;	
    public int goldSpent;
    public int item0;
    public int item1;
    public int item2;
    public int item3;
    public int item4;
    public int item5;
    public int item6;
    public int itemsPurchased;
    public int killingSprees;
    public int largestCriticalStrike;
    public int largestKillingSpree;
    public int largestMultiKill;
    public int legendaryItemsCreated;
    public int level;
    public int magicDamageDealtPlayer;
    public int magicDamageDealtToChampions;
    public int magicDamageTaken;
    public int minionsDenied;
    public int minionsKilled;
    public int neutralMinionsKilled;
    public int neutralMinionsKilledEnemyJungle;
    public int neutralMinionsKilledYourJungle;
    public bool nexusKilled;
    public int nodeCapture;	
    public int nodeCaptureAssist;
    public int nodeNeutralize;	
    public int nodeNeutralizeAssist;	
    public int numDeaths;	
    public int numItemsBought;	
    public int objectivePlayerScore;	
    public int pentaKills;	
    public int physicalDamageDealtPlayer;	
    public int physicalDamageDealtToChampions;	
    public int physicalDamageTaken;	
    public int quadraKills;	
    public int sightWardsBought;	
    public int spell1Cast;
    public int spell2Cast;
    public int spell3Cast;
    public int spell4Cast;
    public int summonSpell1Cast;	
    public int summonSpell2Cast;	
    public int superMonsterKilled;	
    public int team;	
    public int teamObjective;	
    public int timePlayed;	
    public int totalDamageDealt;	
    public int totalDamageDealtToChampions;	
    public int totalDamageTaken;	
    public int totalHeal;	
    public int totalPlayerScore;	
    public int totalScoreRank;	
    public int totalTimeCrowdControlDealt;	
    public int totalUnitsHealed;	
    public int tripleKills;	
    public int trueDamageDealtPlayer;	
    public int trueDamageDealtToChampions;	
    public int trueDamageTaken;	
    public int turretsKilled;	
    public int unrealKills;	
    public int victoryPointTotal;	
    public int visionWardsBought;	
    public int wardKilled;
    public int wardPlaced;
    public bool win;

    public string Summary()
    {
        string str = "";

        str += "assists: " + assists + "<br/>";
        str += "barracksKilled: " + barracksKilled + "<br/>";
        str += "championsKilled: " + championsKilled + "<br/>";
        str += "combatPlayerScore: " + combatPlayerScore + "<br/>";
        str += "consumablesPurchased: " + consumablesPurchased + "<br/>";
        str += "damageDealtPlayer: " + damageDealtPlayer + "<br/>";
        str += "doubleKills: " + doubleKills + "<br/>";
        str += "firstBlood: " + firstBlood + "<br/>";
        str += "gold: " + gold + "<br/>";
        str += "goldEarned: " + goldEarned + "<br/>";
        str += "goldSpent: " + goldSpent + "<br/>";
        str += "item0: " + item0 + "<br/>";
        str += "item1: " + item1 + "<br/>";
        str += "item2: " + item2 + "<br/>";
        str += "item3: " + item3 + "<br/>";
        str += "item4: " + item4 + "<br/>";
        str += "item5: " + item5 + "<br/>";
        str += "item6: " + item6 + "<br/>";
        str += "itemsPurchased: " + itemsPurchased + "<br/>";
        str += "killingSprees: " + killingSprees + "<br/>";
        str += "largestCriticalStrike: " + largestCriticalStrike + "<br/>";
        str += "largestKillingSpree: " + largestKillingSpree + "<br/>";
        str += "largestMultiKill: " + largestMultiKill + "<br/>";
        str += "legendaryItemsCreated: " + legendaryItemsCreated + "<br/>";
        str += "level: " + level + "<br/>";
        str += "magicDamageDealtPlayer: " + magicDamageDealtPlayer + "<br/>";
        str += "magicDamageDealtToChampions: " + magicDamageDealtToChampions + "<br/>";
        str += "magicDamageTaken: " + magicDamageTaken + "<br/>";
        str += "minionsDenied: " + minionsDenied + "<br/>";
        str += "minionsKilled: " + minionsKilled + "<br/>";
        str += "neutralMinionsKilled: " + neutralMinionsKilled + "<br/>";
        str += "neutralMinionsKilledEnemyJungle: " + neutralMinionsKilledEnemyJungle + "<br/>";
        str += "neutralMinionsKilledYourJungle: " + neutralMinionsKilledYourJungle + "<br/>";
        str += "nexusKilled: " + nexusKilled + "<br/>";
        str += "nodeCapture: " + nodeCapture + "<br/>";
        str += "nodeCaptureAssist: " + nodeCaptureAssist + "<br/>";
        str += "nodeNeutralize: " + nodeNeutralize + "<br/>";
        str += "nodeNeutralizeAssist: " + nodeNeutralizeAssist + "<br/>";
        str += "numDeaths: " + numDeaths + "<br/>";
        str += "numItemsBought: " + numItemsBought + "<br/>";
        str += "objectivePlayerScore: " + objectivePlayerScore + "<br/>";
        str += "pentaKills: " + pentaKills + "<br/>";
        str += "physicalDamageDealtPlayer: " + physicalDamageDealtPlayer + "<br/>";
        str += "physicalDamageDealtToChampions: " + physicalDamageDealtToChampions + "<br/>";
        str += "physicalDamageTaken: " + physicalDamageTaken + "<br/>";
        str += "quadraKills: " + quadraKills + "<br/>";
        str += "sightWardsBought: " + sightWardsBought + "<br/>";
        str += "spell1Cast: " + spell1Cast + "<br/>";
        str += "spell2Cast: " + spell2Cast + "<br/>";
        str += "spell3Cast: " + spell3Cast + "<br/>";
        str += "spell4Cast: " + spell4Cast + "<br/>";
        str += "summonSpell1Cast: " + summonSpell1Cast + "<br/>";
        str += "summonSpell2Cast: " + summonSpell2Cast + "<br/>";
        str += "superMonsterKilled: " + superMonsterKilled + "<br/>";
        str += "team: " + team + "<br/>";
        str += "teamObjective: " + teamObjective + "<br/>";
        str += "timePlayed: " + timePlayed + "<br/>";
        str += "totalDamageDealt: " + totalDamageDealt + "<br/>";
        str += "totalDamageDealtToChampions: " + totalDamageDealtToChampions + "<br/>";
        str += "totalDamageTaken: " + totalDamageTaken + "<br/>";
        str += "totalHeal: " + totalHeal + "<br/>";
        str += "totalPlayerScore: " + totalPlayerScore + "<br/>";
        str += "totalScoreRank: " + totalScoreRank + "<br/>";
        str += "totalTimeCrowdControlDealt: " + totalTimeCrowdControlDealt + "<br/>";
        str += "totalUnitsHealed: " + totalUnitsHealed + "<br/>";
        str += "tripleKills: " + tripleKills + "<br/>";
        str += "trueDamageDealtPlayer: " + trueDamageDealtPlayer + "<br/>";
        str += "trueDamageDealtToChampions: " + trueDamageDealtToChampions + "<br/>";
        str += "trueDamageTaken: " + trueDamageTaken + "<br/>";
        str += "turretsKilled: " + turretsKilled + "<br/>";
        str += "unrealKills: " + unrealKills + "<br/>";
        str += "victoryPointTotal: " + victoryPointTotal + "<br/>";
        str += "visionWardsBought: " + visionWardsBought + "<br/>";
        str += "wardKilled: " + wardKilled + "<br/>";
        str += "wardPlaced: " + wardPlaced + "<br/>";
        str += "win: " + win;

        return str;
    }
}